POST http://localhost:3000/api/posts/196/comments
Content-Type: application/json

{
	"nickname": "까미언니",
	"content": "우리 까미랑도 친해지면 좋겠어요!",
	"password": "12345"
}

###

GET http://localhost:3000/api/posts/196/comments

###

PUT http://localhost:3000/api/comments/122
Content-Type: application/json

{
	"nickname": "까미언니",
	"content": "우리 까미 생각난당",
	"password": "12345"
}

###

DELETE http://localhost:3000/api/comments/424
Content-Type: application/json

{
  "password": "910208"
}