POST http://localhost:3000/api/groups
Content-Type: application/json

{
	"name": "해피의 일상 기록",
	"password": "1234",
	"imageUrl": "http://localhost:3000/uploads/1725427641362.jpg",
	"isPublic": true,
	"introduction": "해피의 공간에 놀러오세요~"
}

###

POST http://localhost:3000/api/groups
Content-Type: application/json

{
	"name": "해피의 일상 기록123",
	"password": "1234",
	"isPublic": true,
	"introduction": "해피의 공간에 놀러오세요~"
}


###
PUT http://localhost:3000/api/groups/27
Content-Type: application/json

{
	"name": "해피의 일상 기록",
	"password": "1234",
	"imageUrl": "http://localhost:3000/uploads/1725427641362.jpg",
	"isPublic": false,
	"introduction": "해피의 공간에 놀러오세요~"
}

###
DELETE http://localhost:3000/api/groups/19
Content-Type: application/json

{
  "password": "0609"
}

###


GET http://localhost:3000/api/groups/1

###

GET http://localhost:3000/api/groups?sortBy=mostLiked

###

GET http://localhost:3000/api/groups?sortBy=mostPosted&page=2

###
GET http://localhost:3000/api/groups?sortBy=mostBadge

###
GET http://localhost:3000/api/groups?keyword=동호회&sortBy=mostPosted


###
GET http://localhost:3000/api/groups?isPublic=true

###

GET http://localhost:3000/api/groups/1

###
POST http://localhost:3000/api/groups/1/verify-password
Content-Type: application/json

{
	"password": "family123"
}

###
POST http://localhost:3000/api/groups/1/like

###
GET http://localhost:3000/api/groups/1/is-public
