export const GROUPS = [
  {
    id: 1,
    name: "여행 애호가들",
    imageUrl: "http://localhost:3000/uploads/1725006123674.jpeg",
    introduction: "여행을 사랑하는 사람들을 위한 그룹입니다.",
    isPublic: true,
    password: "travel123",
    createdAt: new Date("2023-10-02"),
    likeCount: 10000,
    postCount: 10,
  },
  {
    id: 2,
    name: "음식 애호가들",
    imageUrl: "http://localhost:3000/uploads/1725006123674.jpeg",
    introduction: "레시피와 음식 경험을 공유하는 그룹입니다.",
    isPublic: true,
    password: "foodie123",
    createdAt: new Date("2023-11-15"),
    likeCount: 12000,
    postCount: 8,
  },
  {
    id: 3,
    name: "독서 클럽",
    imageUrl: "http://localhost:3000/uploads/1725006123674.jpeg",
    introduction: "책을 좋아하는 사람들을 위한 그룹입니다.",
    isPublic: true,
    password: "book123",
    createdAt: new Date("2011-09-01"),
    likeCount: 15000,
    postCount: 6,
  },
  {
    id: 4,
    name: "등산 동호회",
    imageUrl: "http://localhost:3000/uploads/1725006123674.jpeg",
    introduction: "등산을 좋아하는 사람들의 모임입니다.",
    isPublic: false,
    password: "hike123",
    createdAt: new Date("2024-08-22"),
    likeCount: 8000,
    postCount: 5,
  },
  {
    id: 5,
    name: "음악 감상",
    imageUrl: "http://localhost:3000/uploads/1725006123674.jpeg",
    introduction: "음악을 사랑하는 사람들의 모임입니다.",
    isPublic: true,
    password: "music123",
    createdAt: new Date("2022-11-15"),
    likeCount: 20000,
    postCount: 7,
  },
  {
    id: 6,
    name: "사진 동호회",
    imageUrl: "http://localhost:3000/uploads/1725006123674.jpeg",
    introduction: "사진 촬영을 즐기는 사람들을 위한 그룹입니다.",
    isPublic: false,
    password: "photo123",
    createdAt: new Date(),
    likeCount: 17000,
    postCount: 4,
  },
  {
    id: 7,
    name: "프로그래밍 스터디",
    imageUrl: "http://localhost:3000/uploads/1725006123674.jpeg",
    introduction: "프로그래밍을 배우고 싶은 사람들의 모임입니다.",
    isPublic: true,
    password: "code123",
    createdAt: new Date(),
    likeCount: 5000,
    postCount: 9,
  },
  {
    id: 8,
    name: "요가 클래스",
    imageUrl: "http://localhost:3000/uploads/1725006123674.jpeg",
    introduction: "요가를 배우고 싶은 사람들을 위한 그룹입니다.",
    isPublic: true,
    password: "yoga123",
    createdAt: new Date(),
    likeCount: 9000,
    postCount: 3,
  },
  {
    id: 9,
    name: "영화 감상 클럽",
    imageUrl: "http://localhost:3000/uploads/1725006123674.jpeg",
    introduction: "영화를 좋아하는 사람들의 모임입니다.",
    isPublic: false,
    password: "movie123",
    createdAt: new Date(),
    likeCount: 14000,
    postCount: 2,
  },
  {
    id: 10,
    name: "요리 연구회",
    imageUrl: "http://localhost:3000/uploads/1725006123674.jpeg",
    introduction: "다양한 요리를 연구하는 모임입니다.",
    isPublic: true,
    password: "cook123",
    createdAt: new Date(),
    likeCount: 25000,
    postCount: 1,
  },
];

export const POSTS = [
  {
    id: 1,
    groupId: 1,
    nickname: "Traveler1",
    title: "일본 여행기",
    imageUrl: "http://localhost:3000/uploads/1725006123674.jpeg",
    content: "일본에서 놀라운 시간을 보냈습니다!",
    tags: "여행, 일본",
    location: "도쿄, 일본",
    moment: new Date("2023-06-15"),
    isPublic: true,
    password: "post123",
    likeCount: 5000,
    commentCount: 3,
    createdAt: new Date(),
  },
  {
    id: 2,
    groupId: 2,
    nickname: "Foodie1",
    title: "최고의 파스타 레시피",
    imageUrl: "http://localhost:3000/uploads/1725006123674.jpeg",
    content: "최고의 파스타 레시피를 공유합니다.",
    tags: "음식, 파스타",
    location: "로마, 이탈리아",
    moment: new Date("2023-07-20"),
    isPublic: true,
    password: "pasta123",
    likeCount: 6000,
    commentCount: 3,
    createdAt: new Date(),
  },
  {
    id: 3,
    groupId: 3,
    nickname: "BookLover",
    title: "독서 목록 추천",
    imageUrl: "http://localhost:3000/uploads/1725006123674.jpeg",
    content: "이번 달 추천 도서를 공유합니다.",
    tags: "독서, 추천도서",
    location: "서울, 한국",
    moment: new Date("2023-08-10"),
    isPublic: true,
    password: "book123",
    likeCount: 5500,
    commentCount: 3,
    createdAt: new Date(),
  },
  {
    id: 4,
    groupId: 4,
    nickname: "HikerJoe",
    title: "한라산 등반기",
    imageUrl: "http://localhost:3000/uploads/1725006123674.jpeg",
    content: "한라산에서의 멋진 경험을 공유합니다.",
    tags: "등산, 한라산",
    location: "제주도, 한국",
    moment: new Date("2023-09-05"),
    isPublic: true,
    password: "hike123",
    likeCount: 3000,
    commentCount: 3,
    createdAt: new Date(),
  },
  {
    id: 5,
    groupId: 5,
    nickname: "MusicFan",
    title: "최고의 재즈 앨범",
    imageUrl: "http://localhost:3000/uploads/1725006123674.jpeg",
    content: "제가 가장 좋아하는 재즈 앨범을 소개합니다.",
    tags: "음악, 재즈",
    location: "뉴올리언스, 미국",
    moment: new Date("2023-10-01"),
    isPublic: true,
    password: "music123",
    likeCount: 8000,
    commentCount: 3,
    createdAt: new Date(),
  },
  {
    id: 6,
    groupId: 6,
    nickname: "PhotoGrapher",
    title: "가을 풍경 사진",
    imageUrl: "http://localhost:3000/uploads/1725006123674.jpeg",
    content: "가을의 멋진 풍경을 찍었습니다.",
    tags: "사진, 가을",
    location: "서울, 한국",
    moment: new Date("2023-11-15"),
    isPublic: true,
    password: "photo123",
    likeCount: 7000,
    commentCount: 3,
    createdAt: new Date(),
  },
  {
    id: 7,
    groupId: 7,
    nickname: "Coder123",
    title: "자바스크립트 기본기",
    imageUrl: "http://localhost:3000/uploads/1725006123674.jpeg",
    content: "자바스크립트 기초를 배워보세요.",
    tags: "프로그래밍, 자바스크립트",
    location: "부산, 한국",
    moment: new Date("2023-12-05"),
    isPublic: true,
    password: "code123",
    likeCount: 4000,
    commentCount: 3,
    createdAt: new Date(),
  },
  {
    id: 8,
    groupId: 8,
    nickname: "YogaLover",
    title: "아침 요가 루틴",
    imageUrl: "http://localhost:3000/uploads/1725006123674.jpeg",
    content: "매일 아침 요가 루틴을 공유합니다.",
    tags: "요가, 루틴",
    location: "서울, 한국",
    moment: new Date("2024-01-10"),
    isPublic: true,
    password: "yoga123",
    likeCount: 3500,
    commentCount: 3,
    createdAt: new Date(),
  },
  {
    id: 9,
    groupId: 9,
    nickname: "MovieBuff",
    title: "최고의 영화 추천",
    imageUrl: "http://localhost:3000/uploads/1725006123674.jpeg",
    content: "이번 달 최고의 영화를 추천합니다.",
    tags: "영화, 추천",
    location: "서울, 한국",
    moment: new Date("2024-02-20"),
    isPublic: true,
    password: "movie123",
    likeCount: 9000,
    commentCount: 3,
    createdAt: new Date(),
  },
  {
    id: 10,
    groupId: 10,
    nickname: "CookMaster",
    title: "제일 맛있는 스파게티 레시피",
    imageUrl: "http://localhost:3000/uploads/1725006123674.jpeg",
    content: "저의 스파게티 레시피를 공유합니다.",
    tags: "요리, 스파게티",
    location: "서울, 한국",
    moment: new Date("2024-03-15"),
    isPublic: true,
    password: "cook123",
    likeCount: 10000,
    commentCount: 3,
    createdAt: new Date(),
  },
];

export const COMMENTS = [
  // Post 1 Comments
  {
    postId: 1, // Updated to match the UUID format
    nickname: "Commenter1",
    content: "와, 일본이 멋져 보이네요!",
    password: "comment123",
    createdAt: new Date(),
  },
  {
    postId: 1,
    nickname: "Commenter2",
    content: "여행기가 정말 생생해요!",
    password: "comment123",
    createdAt: new Date(),
  },
  {
    postId: 1,
    nickname: "Commenter3",
    content: "저도 일본에 가보고 싶어요!",
    password: "comment123",
    createdAt: new Date(),
  },

  // Post 2 Comments
  {
    postId: 2,
    nickname: "Commenter4",
    content: "이 파스타 레시피 정말 최고네요!",
    password: "comment123",
    createdAt: new Date(),
  },
  {
    postId: 2,
    nickname: "Commenter5",
    content: "간단하고 맛있어 보여요!",
    password: "comment123",
    createdAt: new Date(),
  },
  {
    postId: 2,
    nickname: "Commenter6",
    content: "오늘 저녁에 바로 만들어봐야겠어요.",
    password: "comment123",
    createdAt: new Date(),
  },

  // Post 3 Comments
  {
    postId: 3,
    nickname: "Commenter7",
    content: "독서 목록이 정말 유용해요!",
    password: "comment123",
    createdAt: new Date(),
  },
  {
    postId: 3,
    nickname: "Commenter8",
    content: "추천 도서가 마음에 들어요.",
    password: "comment123",
    createdAt: new Date(),
  },
  {
    postId: 3,
    nickname: "Commenter9",
    content: "이번 달에 읽을 책이 생겼어요!",
    password: "comment123",
    createdAt: new Date(),
  },

  // Post 4 Comments
  {
    postId: 4,
    nickname: "Commenter10",
    content: "한라산 등반기 정말 재미있었어요!",
    password: "comment123",
    createdAt: new Date(),
  },
  {
    postId: 4,
    nickname: "Commenter11",
    content: "등산을 좋아하는데, 저도 도전해보고 싶어요.",
    password: "comment123",
    createdAt: new Date(),
  },
  {
    postId: 4,
    nickname: "Commenter12",
    content: "사진이 너무 멋져요!",
    password: "comment123",
    createdAt: new Date(),
  },

  // Post 5 Comments
  {
    postId: 5,
    nickname: "Commenter13",
    content: "재즈 앨범 추천 감사해요!",
    password: "comment123",
    createdAt: new Date(),
  },
  {
    postId: 5,
    nickname: "Commenter14",
    content: "음악 취향이 저와 비슷하네요.",
    password: "comment123",
    createdAt: new Date(),
  },
  {
    postId: 5,
    nickname: "Commenter15",
    content: "추천 앨범 중에서 제 최애가 생겼어요.",
    password: "comment123",
    createdAt: new Date(),
  },

  // Post 6 Comments
  {
    postId: 6,
    nickname: "Commenter16",
    content: "가을 풍경이 정말 아름다워요.",
    password: "comment123",
    createdAt: new Date(),
  },
  {
    postId: 6,
    nickname: "Commenter17",
    content: "사진이 예술 작품 같아요!",
    password: "comment123",
    createdAt: new Date(),
  },
  {
    postId: 6,
    nickname: "Commenter18",
    content: "가을을 만끽할 수 있는 좋은 글이네요.",
    password: "comment123",
    createdAt: new Date(),
  },

  // Post 7 Comments
  {
    postId: 7,
    nickname: "Commenter19",
    content: "자바스크립트 기초 잘 설명해주셨네요.",
    password: "comment123",
    createdAt: new Date(),
  },
  {
    postId: 7,
    nickname: "Commenter20",
    content: "이제 자바스크립트가 좀 이해되네요!",
    password: "comment123",
    createdAt: new Date(),
  },
  {
    postId: 7,
    nickname: "Commenter21",
    content: "정말 필요한 정보였어요.",
    password: "comment123",
    createdAt: new Date(),
  },

  // Post 8 Comments
  {
    postId: 8,
    nickname: "Commenter22",
    content: "아침 요가 루틴이 너무 좋아요!",
    password: "comment123",
    createdAt: new Date(),
  },
  {
    postId: 8,
    nickname: "Commenter23",
    content: "덕분에 아침이 더 활기차졌어요.",
    password: "comment123",
    createdAt: new Date(),
  },
  {
    postId: 8,
    nickname: "Commenter24",
    content: "아침 요가를 시작해봐야겠어요.",
    password: "comment123",
    createdAt: new Date(),
  },

  // Post 9 Comments
  {
    postId: 9,
    nickname: "Commenter25",
    content: "이 영화 리스트 정말 마음에 들어요!",
    password: "comment123",
    createdAt: new Date(),
  },
  {
    postId: 9,
    nickname: "Commenter26",
    content: "추천 영화 중 몇 개는 못 봤네요.",
    password: "comment123",
    createdAt: new Date(),
  },
  {
    postId: 9,
    nickname: "Commenter27",
    content: "다음 주말에 꼭 봐야겠어요.",
    password: "comment123",
    createdAt: new Date(),
  },

  // Post 10 Comments
  {
    postId: 10,
    nickname: "Commenter28",
    content: "아침 산책이 정말 좋아 보여요!",
    password: "comment123",
    createdAt: new Date(),
  },
  {
    postId: 10,
    nickname: "Commenter29",
    content: "저도 내일부터 산책을 시작해야겠어요.",
    password: "comment123",
    createdAt: new Date(),
  },
  {
    postId: 10,
    nickname: "Commenter30",
    content: "산책 코스 추천 감사해요!",
    password: "comment123",
    createdAt: new Date(),
  },
];


export const BADGES = [
  {
    id: 1,
    name: "우수 기여자",
  },
  {
    id: 2,
    name: "활동 왕",
  },
  {
    id: 3,
    name: "최고의 인기글",
  },
  {
    id: 4,
    name: "베스트 리뷰어",
  },
  {
    id: 5,
    name: "친절한 멤버",
  },
  {
    id: 6,
    name: "모범 회원",
  },
  {
    id: 7,
    name: "콘텐츠 제작자",
  },
  {
    id: 8,
    name: "핫 아이템",
  },
  {
    id: 9,
    name: "장기 활동 회원",
  },
  {
    id: 10,
    name: "열정적인 참여자",
  },
];

export const GROUPBADGES = [
  { groupId: 1, badgeId: 1 },
  { groupId: 2, badgeId: 2 },
  { groupId: 3, badgeId: 3 },
  { groupId: 4, badgeId: 4 },
  { groupId: 5, badgeId: 5 },
  { groupId: 6, badgeId: 6 },
  { groupId: 7, badgeId: 7 },
  { groupId: 8, badgeId: 8 },
  { groupId: 9, badgeId: 9 },
  { groupId: 10, badgeId: 10 },
];

// export const GROUPLIKES = [
//   { groupId: 1, count: 150},
//   { groupId: 2, count: 23},
//   { groupId: 3, count: 153 },
//   { groupId: 4, count: 15 },
//   { groupId: 5, count: 100 },
//   { groupId: 6, count: 1 },
//   { groupId: 7, count: 70 },
//   { groupId: 8, count: 12 },
//   { groupId: 9, count: 23 },
//   { groupId: 10, count: 10}
// ];

// export const POSTLIKES = [
//   { postId: 1, count: 150},
//   { postId: 2, count: 150},
//   { postId: 3, count: 150},
//   { postId: 4, count: 150},
//   { postId: 5, count: 150},
//   { postId: 6, count: 150},
//   { postId: 7, count: 150},
//   { postId: 8, count: 150},
//   { postId: 9, count: 150},
//   { postId: 10, count: 150}
// ];
